mqtt:
  hostname: 192.168.178.105
  port: 1883
  user: j4205
  password: 5962ae44
deviceName: j4205
client_id: j4205
timezone: Europe/Berlin
update_interval: 60
sensors:
  temperature: true
  clock_speed: true
  disk_use: true
  memory_use: true
  cpu_usage: true
  load_1m: true
  load_5m: true
  load_15m: true
  net_tx: true
  net_rx: true
  swap_usage: true
  power_status: true
  power_source: true
  last_boot: true
  hostname: true
  host_ip: true
  host_os: true
  host_arch: true
  last_message: true
  updates: true
  wifi_strength: false
  wifi_ssid: false
  external_drives:
    lv_mac: /mnt/mac
    lv_frigate: /mnt/frigate